
['kodiaq'] = {
		['name'] = 'Kodiaq',
		['brand'] = 'Skoda',
		['model'] = 'kodiaq',
		['price'] = 890 000,
		['category'] = 'skoda',
		['hash'] = 'kodiaq',
		['shop'] = 'pdm',
	},
   ['octav20'] = {
		['name'] = 'Octavia 2020',
		['brand'] = 'Skoda',
		['model'] = 'octav20',
		['price'] = 859 900,
		['category'] = 'skoda',
		['hash'] = 'octav20',
		['shop'] = 'pdm',
	},
   ['o3civil'] = {
		['name'] = 'Octavia ',
		['brand'] = 'Skoda',
		['model'] = 'o3civil',
		['price'] = 299 000,
		['category'] = 'skoda',
		['hash'] = 'o3civil',
		['shop'] = 'pdm',
	},
   ['skodatrg'] = {
		['name'] = 'Rapid',
		['brand'] = 'Skoda',
		['model'] = 'skodatrg',
		['price'] = 524 300,
		['category'] = 'skoda',
		['hash'] = 'skodatrg',
		['shop'] = 'pdm',
	},
   ['octavia17'] = {
		['name'] = 'Octavia 2017',
		['brand'] = 'Skoda',
		['model'] = 'octavia17',
		['price'] = 377 300,
		['category'] = 'skoda',
		['hash'] = 'octavia17',
		['shop'] = 'pdm',
	},
   ['superb'] = {
		['name'] = 'Superb sedan',
		['brand'] = 'Skoda',
		['model'] = 'superb',
		['price'] = 230 000,
		['category'] = 'skoda',
		['hash'] = 'superb',
		['shop'] = 'pdm',
	},
   ['supik'] = {
		['name'] = 'Superb combi',
		['brand'] = 'Skoda',
		['model'] = 'supik',
		['price'] = 240 000,
		['category'] = 'skoda',
		['hash'] = 'supik',
		['shop'] = 'pdm',
	},
   ['ctsuperb'] = {
		['name'] = 'Superb 2021 sedan',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb',
		['price'] = 1 140 000,
		['category'] = 'skoda',
		['hash'] = 'ctsuperb',
		['shop'] = 'pdm',
	},
   ['ctsuperb2'] = {
		['name'] = 'Superb 2021 combi',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb2',
		['price'] = 1 140 000,
		['category'] = 'skoda',
		['hash'] = 'ctsuperb2',
		['shop'] = 'pdm',
	},
   ['ctsuperb3'] = {
		['name'] = 'Superb 2021 scout',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb3',
		['price'] = 1 240 000,
		['category'] = 'skoda',
		['hash'] = 'ctsuperb3',
		['shop'] = 'pdm',
	},
	['fabia'] = {
		 ['name'] = 'Fabia 2022',
		 ['brand'] = 'Skoda',
		 ['model'] = 'fabia',
		 ['price'] = 339 000,
		 ['category'] = 'skoda',
		 ['hash'] = 'fabia',
		 ['shop'] = 'pdm',
		},
   
		['clssb'] = {
			['name'] = 'VIP - Brabus CLS800',
			['brand'] = 'Mercedes',
			['model'] = 'clssb',
			['price'] = 35000000,
			['category'] = 'mercedes',
			['hash'] = 'clssb',
			['shop'] = 'pdm',
		},
		['brabus'] = {
			['name'] = 'VIP - Brabus S900 Rocket',
			['brand'] = 'Mercedes',
			['model'] = 'brabus',
			['price'] = 35000000,
			['category'] = 'mercedes',
			['hash'] = 'brabus',
			['shop'] = 'pdm',
		},
		['g4x4'] = {
			['name'] = 'VIP - Brabus G700 4X4/2',
			['brand'] = 'Mercedes',
			['model'] = 'g4x4',
			['price'] = 35000000,
			['category'] = 'mercedes',
			['hash'] = 'g4x4',
			['shop'] = 'pdm',
		},
		['g800'] = {
			['name'] = 'Brabus G800',
			['brand'] = 'Mercedes',
			['model'] = 'g800',
			['price'] = 12 000 000,
			['category'] = 'mercedes',
			['hash'] = 'g800',
			['shop'] = 'pdm',
		},
		['bg700w'] = {
			['name'] = 'Brabus GV12 900',
			['brand'] = 'Mercedes',
			['model'] = 'bg700w',
			['price'] = 13 500 000,
			['category'] = 'mercedes',
			['hash'] = 'bg700w',
			['shop'] = 'pdm',
		},

	['2020g900'] = {
		['name'] = 'Brabus G900',
		['brand'] = 'Mercedes',
		['model'] = '2020g900',
		['price'] = 9 500 000,
		['category'] = 'mercedes',
		['hash'] = '2020g900',
		['shop'] = 'pdm',
	},
   ['brabusrocket900'] = {
		['name'] = 'Brabus Rocket',
		['brand'] = 'Mercedes',
		['model'] = 'brabusrocket900',
		['price'] = 8 000 000,
		['category'] = 'mercedes',
		['hash'] = 'brabusrocket900',
		['shop'] = 'pdm',
	},
   ['g900rocket21'] = {
		['name'] = 'g900rocket21',
		['brand'] = 'Mercedes',
		['model'] = 'g900rocket21',
		['price'] = 8 500 000,
		['category'] = 'mercedes',
		['hash'] = 'g900rocket21',
		['shop'] = 'pdm',
	},
   ['s63amg21'] = {
		['name'] = 's63amg21',
		['brand'] = 'Mercedes',
		['model'] = 's63amg21',
		['price'] = 2 250 000,
		['category'] = 'mercedes',
		['hash'] = 's63amg21',
		['shop'] = 'pdm',
	},
   ['mbs2021'] = {
		['name'] = 'mbs2021',
		['brand'] = 'Mercedes',
		['model'] = 'mbs2021',
		['price'] = 3 500 000,
		['category'] = 'mercedes',
		['hash'] = 'mbs2021',
		['shop'] = 'pdm',
	},
   ['17octavia'] = {
		['name'] = '17octavia',
		['brand'] = 'Skoda',
		['model'] = '17octavia',
		['price'] = 370 000,
		['category'] = 'ostatni',
		['hash'] = '17octavia',
		['shop'] = 'pdm',
	},
   ['emperor'] = {
		['name'] = 'emperor',
		['brand'] = 'Skoda',
		['model'] = 'emperor',
		['price'] = 50000,
		['category'] = 'ostatni',
		['hash'] = 'emperor',
		['shop'] = 'pdm',
	},
   ['landstalker'] = {
		['name'] = 'landstalker',
		['brand'] = 'Skoda',
		['model'] = 'landstalker',
		['price'] = 50000,
		['category'] = 'ostatni',
		['hash'] = 'landstalker',
		['shop'] = 'pdm',
	},
   ['skoda100'] = {
		['name'] = 'skoda100',
		['brand'] = 'Skoda',
		['model'] = 'skoda100',
		['price'] = 30000,
		['category'] = 'ostatni',
		['hash'] = 'skoda100',
		['shop'] = 'pdm',
	},
   ['sovrs'] = {
		['name'] = 'sovrs',
		['brand'] = 'Skoda',
		['model'] = 'sovrs',
		['price'] = 150000,
		['category'] = 'ostatni',
		['hash'] = 'sovrs',
		['shop'] = 'pdm',
	},
   ['stratum'] = {
		['name'] = 'stratum',
		['brand'] = 'Skoda',
		['model'] = 'stratum',
		['price'] = 50000,
		['category'] = 'ostatni',
		['hash'] = 'stratum',
		['shop'] = 'pdm',
	},
   ['superb'] = {
		['name'] = 'superb',
		['brand'] = 'Skoda',
		['model'] = 'superb',
		['price'] = 200000,
		['category'] = 'ostatni',
		['hash'] = 'superb',
		['shop'] = 'pdm',
	},
   ['ctsuperb'] = {
		['name'] = 'ctsuperb',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb',
		['price'] = 350000,
		['category'] = 'ostatni',
		['hash'] = 'ctsuperb',
		['shop'] = 'pdm',
	},
   ['ctsuperb2'] = {
		['name'] = 'ctsuperb2',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb2',
		['price'] = 350000,
		['category'] = 'ostatni',
		['hash'] = 'ctsuperb2',
		['shop'] = 'pdm',
	},
   ['ctsuperb3'] = {
		['name'] = 'ctsuperb3',
		['brand'] = 'Skoda',
		['model'] = 'ctsuperb3',
		['price'] = 350000,
		['category'] = 'ostatni',
		['hash'] = 'ctsuperb3',
		['shop'] = 'pdm',
	},
   ['amarok'] = {
		['name'] = 'amarok',
		['brand'] = 'Volks',
		['model'] = 'amarok',
		['price'] = 250000,
		['category'] = 'ostatni',
		['hash'] = 'amarok',
		['shop'] = 'pdm',
	},
   ['fox'] = {
		['name'] = 'fox',
		['brand'] = 'Volks',
		['model'] = 'fox',
		['price'] = 50000,
		['category'] = 'ostatni',
		['hash'] = 'fox',
		['shop'] = 'pdm',
	},
   ['golf75r'] = {
		['name'] = 'golf75r',
		['brand'] = 'Volks',
		['model'] = 'golf75r',
		['price'] = 250000,
		['category'] = 'ostatni',
		['hash'] = 'golf75r',
		['shop'] = 'pdm',
	},
   ['jetta'] = {
		['name'] = 'jetta',
		['brand'] = 'Volks',
		['model'] = 'jetta',
		['price'] = 75000,
		['category'] = 'ostatni',
		['hash'] = 'jetta',
		['shop'] = 'pdm',
	},
   ['passat'] = {
		['name'] = 'passat',
		['brand'] = 'Volks',
		['model'] = 'passat',
		['price'] = 50000,
		['category'] = 'ostatni',
		['hash'] = 'passat',
		['shop'] = 'pdm',
	},
   ['polo2018'] = {
		['name'] = 'polo2018',
		['brand'] = 'Volks',
		['model'] = 'polo2018',
		['price'] = 100000,
		['category'] = 'ostatni',
		['hash'] = 'polo2018',
		['shop'] = 'pdm',
	},
   ['scijo'] = {
		['name'] = 'scijo',
		['brand'] = 'Volks',
		['model'] = 'scijo',
		['price'] = 85000,
		['category'] = 'ostatni',
		['hash'] = 'scijo',
		['shop'] = 'pdm',
	},
   ['tiguan'] = {
		['name'] = 'tiguan',
		['brand'] = 'Volks',
		['model'] = 'tiguan',
		['price'] = 150000,
		['category'] = 'ostatni',
		['hash'] = 'tiguan',
		['shop'] = 'pdm',
	},
   ['virtus2020'] = {
		['name'] = 'virtus2020',
		['brand'] = 'Volks',
		['model'] = 'virtus2020',
		['price'] = 175000,
		['category'] = 'ostatni',
		['hash'] = 'virtus2020',
		['shop'] = 'pdm',
	},
   ['vwtoua19cf'] = {
		['name'] = 'vwtoua19cf',
		['brand'] = 'Volks',
		['model'] = 'vwtoua19cf',
		['price'] = 150000,
		['category'] = 'ostatni',
		['hash'] = 'vwtoua19cf',
		['shop'] = 'pdm',
	},
   
	['2021rs7'] = {
		['name'] = 'RS7 2021',
		['brand'] = 'Audi',
		['model'] = '2021rs7',
		['price'] = 950000,
		['category'] = 'audi',
		['hash'] = '2021rs7',
		['shop'] = 'pdm',
	},
   ['q7'] = {
		['name'] = 'Q7',
		['brand'] = 'Audi',
		['model'] = 'q7',
		['price'] = 750000,
		['category'] = 'audi',
		['hash'] = 'q7',
		['shop'] = 'pdm',
	},
   ['r82020'] = {
		['name'] = 'R8 2020',
		['brand'] = 'Audi',
		['model'] = 'r82020',
		['price'] = 1500000,
		['category'] = 'audi',
		['hash'] = 'r82020',
		['shop'] = 'pdm',
	},
   ['rs3'] = {
		['name'] = 'RS3',
		['brand'] = 'Audi',
		['model'] = 'rs3',
		['price'] = 350000,
		['category'] = 'audi',
		['hash'] = 'rs3',
		['shop'] = 'pdm',
	},
   ['rs4avant'] = {
		['name'] = 'RS4 Avant',
		['brand'] = 'Audi',
		['model'] = 'rs4avant',
		['price'] = 450000,
		['category'] = 'audi',
		['hash'] = 'rs4avant',
		['shop'] = 'pdm',
	},
   ['rs5'] = {
		['name'] = 'RS5',
		['brand'] = 'Audi',
		['model'] = 'rs5',
		['price'] = 550000,
		['category'] = 'audi',
		['hash'] = 'rs5',
		['shop'] = 'pdm',
	},
   ['rs6'] = {
		['name'] = 'RS6',
		['brand'] = 'Audi',
		['model'] = 'rs6',
		['price'] = 650000,
		['category'] = 'audi',
		['hash'] = 'rs6',
		['shop'] = 'pdm',
	},
   ['17m760i'] = {
		['name'] = 'M760i',
		['brand'] = 'Bmw',
		['model'] = '17m760i',
		['price'] = 1500000,
		['category'] = 'bmw',
		['hash'] = '17m760i',
		['shop'] = 'pdm',
	},
   ['22m3'] = {
		['name'] = '22m3',
		['brand'] = 'Bmw',
		['model'] = '22m3',
		['price'] = 150000,
		['category'] = 'bmw',
		['hash'] = '22m3',
		['shop'] = 'pdm',
	},
   ['e30'] = {
		['name'] = 'E30',
		['brand'] = 'Bmw',
		['model'] = 'e30',
		['price'] = 250000,
		['category'] = 'bmw',
		['hash'] = 'e30',
		['shop'] = 'pdm',
	},
   ['f10m5'] = {
		['name'] = 'F10 M5',
		['brand'] = 'Bmw',
		['model'] = 'f10m5',
		['price'] = 350000,
		['category'] = 'bmw',
		['hash'] = 'f10m5',
		['shop'] = 'pdm',
	},
   ['i8'] = {
		['name'] = 'I8',
		['brand'] = 'Bmw',
		['model'] = 'i8',
		['price'] = 350000,
		['category'] = 'bmw',
		['hash'] = 'i8',
		['shop'] = 'pdm',
	},
   ['m2'] = {
		['name'] = 'M2',
		['brand'] = 'Bmw',
		['model'] = 'm2',
		['price'] = 550000,
		['category'] = 'bmw',
		['hash'] = 'm2',
		['shop'] = 'pdm',
	},
   ['m3e46'] = {
		['name'] = 'M3 E46',
		['brand'] = 'Bmw',
		['model'] = 'm3e46',
		['price'] = 90000,
		['category'] = 'bmw',
		['hash'] = 'm3e46',
		['shop'] = 'pdm',
	},
   ['m4comp'] = {
		['name'] = 'M4 Comp',
		['brand'] = 'Bmw',
		['model'] = 'm4comp',
		['price'] = 690000,
		['category'] = 'bmw',
		['hash'] = 'm4comp',
		['shop'] = 'pdm',
	},
   ['m516'] = {
		['name'] = 'M5 2016',
		['brand'] = 'Bmw',
		['model'] = 'm516',
		['price'] = 500000,
		['category'] = 'bmw',
		['hash'] = 'm516',
		['shop'] = 'pdm',
	},
   ['m5e60'] = {
		['name'] = 'M5 E60',
		['brand'] = 'Bmw',
		['model'] = 'm5e60',
		['price'] = 400000,
		['category'] = 'bmw',
		['hash'] = 'm5e60',
		['shop'] = 'pdm',
	},
   ['m5f90'] = {
		['name'] = 'M5 F90.',
		['brand'] = 'Bmw',
		['model'] = 'm5f90',
		['price'] = 800000,
		['category'] = 'bmw',
		['hash'] = 'm5f90',
		['shop'] = 'pdm',
	},
   ['rmodm4gts'] = {
		['name'] = 'M4 GTS',
		['brand'] = 'Bmw',
		['model'] = 'rmodm4gts',
		['price'] = 950000,
		['category'] = 'bmw',
		['hash'] = 'rmodm4gts',
		['shop'] = 'pdm',
	},
   ['x5e53'] = {
		['name'] = 'X5 E53',
		['brand'] = 'Bmw',
		['model'] = 'x5e53',
		['price'] = 95000,
		['category'] = 'bmw',
		['hash'] = 'x5e53',
		['shop'] = 'pdm',
	},
   ['x6m'] = {
		['name'] = 'X6M',
		['brand'] = 'Bmw',
		['model'] = 'x6m',
		['price'] = 350000,
		['category'] = 'bmw',
		['hash'] = 'x6m',
		['shop'] = 'pdm',
	},
   ['fairlane64'] = {
		['name'] = 'Fairlane64',
		['brand'] = 'Ford',
		['model'] = 'fairlane64',
		['price'] = 150000,
		['category'] = 'ford',
		['hash'] = 'fairlane64',
		['shop'] = 'pdm',
	},
   ['focus200'] = {
		['name'] = 'Focus 200',
		['brand'] = 'Ford',
		['model'] = 'focus200',
		['price'] = 25000,
		['category'] = 'ford',
		['hash'] = 'focus200',
		['shop'] = 'pdm',
	},
   ['focusrs'] = {
		['name'] = 'Focus RS',
		['brand'] = 'Ford',
		['model'] = 'focusrs',
		['price'] = 450000,
		['category'] = 'ford',
		['hash'] = 'focusrs',
		['shop'] = 'pdm',
	},
   ['fordst'] = {
		['name'] = 'Focus ST',
		['brand'] = 'Ford',
		['model'] = 'fordst',
		['price'] = 150000,
		['category'] = 'ford',
		['hash'] = 'fordst',
		['shop'] = 'pdm',
	},
   ['gt17'] = {
		['name'] = 'GT 17',
		['brand'] = 'Ford',
		['model'] = 'gt17',
		['price'] = 3250000,
		['category'] = 'ford',
		['hash'] = 'gt17',
		['shop'] = 'pdm',
	},
   ['mustang2015'] = {
		['name'] = 'Mustang 2015',
		['brand'] = 'Ford',
		['model'] = 'mustang2015',
		['price'] = 950000,
		['category'] = 'ford',
		['hash'] = 'mustang2015',
		['shop'] = 'pdm',
	},
   ['mustang2018'] = {
		['name'] = 'Mustang 2018',
		['brand'] = 'Ford',
		['model'] = 'mustang2018',
		['price'] = 1150000,
		['category'] = 'ford',
		['hash'] = 'mustang2018',
		['shop'] = 'pdm',
	},
   ['raptor'] = {
		['name'] = 'Raptor',
		['brand'] = 'Ford',
		['model'] = 'raptor',
		['price'] = 850000,
		['category'] = 'ford',
		['hash'] = 'raptor',
		['shop'] = 'pdm',
	},
   ['rmodmustang'] = {
		['name'] = 'Mustang',
		['brand'] = 'Ford',
		['model'] = 'rmodmustang',
		['price'] = 2050000,
		['category'] = 'ford',
		['hash'] = 'rmodmustang',
		['shop'] = 'pdm',
	},
   ['thr'] = {
		['name'] = 'THR',
		['brand'] = 'Ford',
		['model'] = 'thr',
		['price'] = 150000,
		['category'] = 'ford',
		['hash'] = 'thr',
		['shop'] = 'pdm',
	},
   ['450crf'] = {
		['name'] = '450crf',
		['brand'] = 'Motorky',
		['model'] = '450crf',
		['price'] = 190000,
		['category'] = 'motorky',
		['hash'] = '450crf',
		['shop'] = 'pdm',
	},
   ['cbr1000rrr'] = {
		['name'] = 'cbr1000rrr',
		['brand'] = 'Motorky',
		['model'] = 'cbr1000rrr',
		['price'] = 250000,
		['category'] = 'motorky',
		['hash'] = 'cbr1000rrr',
		['shop'] = 'pdm',
	},
   ['fatboy1'] = {
		['name'] = 'fatboy1',
		['brand'] = 'Motorky',
		['model'] = 'fatboy1',
		['price'] = 150000,
		['category'] = 'motorky',
		['hash'] = 'fatboy1',
		['shop'] = 'pdm',
	},
   ['fatboy2'] = {
		['name'] = 'fatboy2',
		['brand'] = 'Motorky',
		['model'] = 'fatboy2',
		['price'] = 160000,
		['category'] = 'motorky',
		['hash'] = 'fatboy2',
		['shop'] = 'pdm',
	},
   ['fz07'] = {
		['name'] = 'fz07',
		['brand'] = 'Motorky',
		['model'] = 'fz07',
		['price'] = 260000,
		['category'] = 'motorky',
		['hash'] = 'fz07',
		['shop'] = 'pdm',
	},
   ['hcbr17'] = {
		['name'] = 'hcbr17',
		['brand'] = 'Motorky',
		['model'] = 'hcbr17',
		['price'] = 250000,
		['category'] = 'motorky',
		['hash'] = 'hcbr17',
		['shop'] = 'pdm',
	},
   ['hvrod'] = {
		['name'] = 'hvrod',
		['brand'] = 'Motorky',
		['model'] = 'hvrod',
		['price'] = 150000,
		['category'] = 'motorky',
		['hash'] = 'hvrod',
		['shop'] = 'pdm',
	},
   ['mt03'] = {
		['name'] = 'mt03',
		['brand'] = 'Motorky',
		['model'] = 'mt03',
		['price'] = 150000,
		['category'] = 'motorky',
		['hash'] = 'mt03',
		['shop'] = 'pdm',
	},
   ['rc'] = {
		['name'] = 'rc',
		['brand'] = 'Motorky',
		['model'] = 'rc',
		['price'] = 250000,
		['category'] = 'motorky',
		['hash'] = 'rc',
		['shop'] = 'pdm',
	},
   ['softail1'] = {
		['name'] = 'softail1',
		['brand'] = 'Motorky',
		['model'] = 'softail1',
		['price'] = 250000,
		['category'] = 'motorky',
		['hash'] = 'softail1',
		['shop'] = 'pdm',
	},
   ['yzfr6'] = {
		['name'] = 'yzfr6',
		['brand'] = 'Motorky',
		['model'] = 'yzfr6',
		['price'] = 250000,
		['category'] = 'motorky',
		['hash'] = 'yzfr6',
		['shop'] = 'pdm',
	},
   ['zx10'] = {
		['name'] = 'zx10',
		['brand'] = 'Motorky',
		['model'] = 'zx10',
		['price'] = 310000,
		['category'] = 'motorky',
		['hash'] = 'zx10',
		['shop'] = 'pdm',
	},
   ['zx10r'] = {
		['name'] = 'zx10r',
		['brand'] = 'Motorky',
		['model'] = 'zx10r',
		['price'] = 340000,
		['category'] = 'motorky',
		['hash'] = 'zx10r',
		['shop'] = 'pdm',
	},
   ['models'] = {
		['name'] = 'ModelS',
		['brand'] = 'Ostatni',
		['model'] = 'models',
		['price'] = 2150000,
		['category'] = 'ostatni',
		['hash'] = 'models',
		['shop'] = 'pdm',
	},
   ['16charger'] = {
		['name'] = '16charger',
		['brand'] = 'Ostatni',
		['model'] = '16charger',
		['price'] = 700000,
		['category'] = 'ostatni',
		['hash'] = '16charger',
		['shop'] = 'pdm',
	},
   ['16challenger'] = {
		['name'] = '16challenger',
		['brand'] = 'Ostatni',
		['model'] = '16challenger',
		['price'] = 850000,
		['category'] = 'ostatni',
		['hash'] = '16challenger',
		['shop'] = 'pdm',
	},
   ['fastback'] = {
		['name'] = 'fastback',
		['brand'] = 'Ostatni',
		['model'] = 'fastback',
		['price'] = 350000,
		['category'] = 'ostatni',
		['hash'] = 'fastback',
		['shop'] = 'pdm',
	},
   ['ram2016'] = {
		['name'] = 'ram2016',
		['brand'] = 'Ostatni',
		['model'] = 'ram2016',
		['price'] = 450000,
		['category'] = 'ostatni',
		['hash'] = 'ram2016',
		['shop'] = 'pdm',
	},
   ['C7'] = {
		['name'] = 'C7',
		['brand'] = 'Ostatni',
		['model'] = 'C7',
		['price'] = 635000,
		['category'] = 'ostatni',
		['hash'] = 'C7',
		['shop'] = 'pdm',
	},
   ['z20'] = {
		['name'] = 'z20',
		['brand'] = 'Ostatni',
		['model'] = 'z20',
		['price'] = 150000,
		['category'] = 'ostatni',
		['hash'] = 'z20',
		['shop'] = 'pdm',
	},
   ['zl2017'] = {
		['name'] = 'zl2017',
		['brand'] = 'Ostatni',
		['model'] = 'zl2017',
		['price'] = 450000,
		['category'] = 'ostatni',
		['hash'] = 'zl2017',
		['shop'] = 'pdm',
	},
   ['2019merf'] = {
		['name'] = '2019merf',
		['brand'] = 'Mercedes',
		['model'] = '2019merf',
		['price'] = 650000,
		['category'] = 'mercedes',
		['hash'] = '2019merf',
		['shop'] = 'pdm',
	},
   ['2021gls63'] = {
		['name'] = '2021gls63',
		['brand'] = 'Mercedes',
		['model'] = '2021gls63',
		['price'] = 1250000,
		['category'] = 'mercedes',
		['hash'] = '2021gls63',
		['shop'] = 'pdm',
	},
   ['4444'] = {
		['name'] = '4444',
		['brand'] = 'Mercedes',
		['model'] = '4444',
		['price'] = 1850000,
		['category'] = 'mercedes',
		['hash'] = '4444',
		['shop'] = 'pdm',
	},
   ['500w124'] = {
		['name'] = '500w124',
		['brand'] = 'Mercedes',
		['model'] = '500w124',
		['price'] = 1150000,
		['category'] = 'mercedes',
		['hash'] = '500w124',
		['shop'] = 'pdm',
	},
   ['600sel'] = {
		['name'] = '600sel',
		['brand'] = 'Mercedes',
		['model'] = '600sel',
		['price'] = 900000,
		['category'] = 'mercedes',
		['hash'] = '600sel',
		['shop'] = 'pdm',
	},
   ['brabus4x4'] = {
		['name'] = 'brabus4x4',
		['brand'] = 'Mercedes',
		['model'] = 'brabus4x4',
		['price'] = 2350000,
		['category'] = 'mercedes',
		['hash'] = 'brabus4x4',
		['shop'] = 'pdm',
	},
   ['brabus700'] = {
		['name'] = 'brabus700',
		['brand'] = 'Mercedes',
		['model'] = 'brabus700',
		['price'] = 2500000,
		['category'] = 'mercedes',
		['hash'] = 'brabus700',
		['shop'] = 'pdm',
	},
   ['c63'] = {
		['name'] = 'c63',
		['brand'] = 'Mercedes',
		['model'] = 'c63',
		['price'] = 1150000,
		['category'] = 'mercedes',
		['hash'] = 'c63',
		['shop'] = 'pdm',
	},
   ['c63s'] = {
		['name'] = 'c63s',
		['brand'] = 'Mercedes',
		['model'] = 'c63s',
		['price'] = 1500000,
		['category'] = 'mercedes',
		['hash'] = 'c63s',
		['shop'] = 'pdm',
	},
   ['cls2015'] = {
		['name'] = 'cls2015',
		['brand'] = 'Mercedes',
		['model'] = 'cls2015',
		['price'] = 1200000,
		['category'] = 'mercedes',
		['hash'] = 'cls2015',
		['shop'] = 'pdm',
	},
   ['e63estate'] = {
		['name'] = 'e63estate',
		['brand'] = 'Mercedes',
		['model'] = 'e63estate',
		['price'] = 950000,
		['category'] = 'mercedes',
		['hash'] = 'e63estate',
		['shop'] = 'pdm',
	},
   ['e63s'] = {
		['name'] = 'e63s',
		['brand'] = 'Mercedes',
		['model'] = 'e63s',
		['price'] = 1800000,
		['category'] = 'mercedes',
		['hash'] = 'e63s',
		['shop'] = 'pdm',
	},
   ['s600w220'] = {
		['name'] = 's600w220',
		['brand'] = 'Mercedes',
		['model'] = 's600w220',
		['price'] = 750000,
		['category'] = 'mercedes',
		['hash'] = 's600w220',
		['shop'] = 'pdm',
	},
   ['s63'] = {
		['name'] = 's63',
		['brand'] = 'Mercedes',
		['model'] = 's63',
		['price'] = 2350000,
		['category'] = 'mercedes',
		['hash'] = 's63',
		['shop'] = 'pdm',
	},
   ['s63w222'] = {
		['name'] = 's63w222',
		['brand'] = 'Mercedes',
		['model'] = 's63w222',
		['price'] = 2850000,
		['category'] = 'mercedes',
		['hash'] = 's63w222',
		['shop'] = 'pdm',
	},
   ['180SX'] = {
		['name'] = '180SX',
		['brand'] = 'ostatni',
		['model'] = '180SX',
		['price'] = 650000,
		['category'] = 'ostatni',
		['hash'] = '180SX',
		['shop'] = 'pdm',
	},
   ['gtr'] = {
		['name'] = 'gtr',
		['brand'] = 'ostatni',
		['model'] = 'gtr',
		['price'] = 1800000,
		['category'] = 'ostatni',
		['hash'] = 'gtr',
		['shop'] = 'pdm',
	},
   ['gtrlb2'] = {
		['name'] = 'gtrlb2',
		['brand'] = 'ostatni',
		['model'] = 'gtrlb2',
		['price'] = 2000000,
		['category'] = 'ostatni',
		['hash'] = 'gtrlb2',
		['shop'] = 'pdm',
	},
   ['titan17'] = {
		['name'] = 'titan17',
		['brand'] = 'ostatni',
		['model'] = 'titan17',
		['price'] = 1500000,
		['category'] = 'ostatni',
		['hash'] = 'titan17',
		['shop'] = 'pdm',
	},
   

